### PR TITLE
Fix path to CoreUtility csproj as the repository is now named VS-Plat…

### PR DESCRIPTION
**Pull request by Therzok**
…form

### CODE REVIEW

**Comment by Therzok** [comment]
Found this while experimenting with graph build from MSBuild.

**Review by KirillOsenkov — APPROVED** [review]

**Comment by KirillOsenkov** [comment]
Mind bumping to this commit? Or I can on Tuesday. Great find! Did you know @cdmihai works on static graph?

**Comment by Therzok** [comment]
Yup, I've been watching msbuild closely, hence the prototype for the graph usage for the vsmac build.

**Comment by cdmihai** [comment]
> Yup, I've been watching msbuild closely, hence the prototype for the graph usage for the vsmac build.

Now that sounds interesting :)
Please keep me in the loop about how it goes, and any difficulties and annoyances you encounter while using the graph.

**Pull request merged**
