### PR TITLE
Bring dev/sevoku/pyro-xcode12-xm7-build-bin branch changes over to fsharp-editor

### PR DESCRIPTION
**Pull request by mrward**

### CODE REVIEW

**Comment by nosami** [comment]
This is the wrong base branch. It should be based on https://github.com/xamarin/visualfsharp/blob/fsharp-editor/vsintegration/src/FSharp.Editor/VSMac/InteractiveSession.fs which already contains this fix :)

**Comment by nosami** [comment]
Not sure exactly how we ended up using origin/dev/sevoku/pyro-xcode12-xm7-build-bin as the base branch, but we should use `fsharp-editor` and make sure all commits from the other branch are in it.

**Comment by mrward** [comment]
Yeah - I was basing this off the branch we are currently using. I had a look at the fsharp-editor branch but it is missing some commits from here. So was not sure :)

**Comment by mrward** [comment]
Will create a new PR in a few minutes :)

**Comment by mrward** [comment]
Updated this PR to pull in the changes from sevo's branch into fsharp-editor. Tests pass locally - just waiting to see if they pass on CI here - https://github.com/xamarin/vsmac/pull/3920

**Comment by mrward** [comment]
F# tests are green for vsmac.

**Review by nosami — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
